name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    env:
      PROJECT_PATH: todoApp.xcodeproj
      SCHEME: todoApp 

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -switch /Applications/Xcode_16.app

      - name: Build
        run: xcodebuild clean build -project ${{ env.PROJECT_PATH }} -scheme ${{ env.SCHEME }} -destination 'platform=iOS Simulator,name=iPhone 15'

      # - name: Run tests
      #   run: xcodebuild test -project ${{ env.PROJECT_PATH }} -scheme ${{ env.SCHEME }} -destination 'platform=iOS Simulator,name=iPhone 15'
